version: "3"
services:
  clientsapi:
    build:
      context: Devsu.Banking.Clients
    environment:
      PORT: 5000
      Urls: "http://0.0.0.0:5000"
      ConnectionStrings__DefaultConnection: "Host=clientsdb;Username=postgres;Password=postgres;Database=clientsdb;"
    ports:
      - "5000:5000"

  clientsdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clientsdb
    volumes:
      - ./BaseDatosClientes.sql:/docker-entrypoint-initdb.d/BaseDatosClientes.sql

  accountsapi:
    build:
      context: Devsu.Banking.Accounts
    environment:
      PORT: 5001
      Urls: "http://0.0.0.0:5001"
      ConnectionStrings__DefaultConnection: "Host=accountsdb;Username=postgres;Password=postgres;Database=accountsdb;"
    ports:
      - "5001:5001"

  accountsdb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accountsdb
    volumes:
      - ./BaseDatosCuentas.sql:/docker-entrypoint-initdb.d/BaseDatosCuentas.sql